### ISSUE TITLE
High(er) level library interface?

### ISSUE THREAD

**Issue by hultqvist** [discosultan/KrakenCore#2]
Would you consider accepting pull requests with higher level functions?

A trivial example would be decoding the unix timestamp as seen below.

    public class Trade
    {
        public decimal Price { get; set; }
        public decimal Volume { get; set; }
        public double Time { get; set; }
        public string Side { get; set; }
        public string Type { get; set; }
        public string Misc { get; set; }

        [JsonIgnore]
        public DateTime DateTime => DateTimeOffset.FromUnixTimeSeconds((long)Time).DateTime;
    }

Similarly options to the client methods such as

    ... GetRecentTrades(string pair, DateTime? since = null)

Or even adding client properties allowing hard coded asset pairs.

    new KrakenClient(...).BTCEUR.GetRecentTrades(DateTime.UtcNow.AddDays(-1));

Would you accept these kind of contributions into the core library?
Alternatives would be a wrapper but it would have to duplicate all models.

**Comment by discosultan** [comment]
I've been thinking about it as well, but haven't made up my mind on what is the best approach:

- Keep the library as low level as possible and force consumers to perform any kind of conversion (build a wrapper, for example)
- Change core models to contain data types familiar to .NET devs (`DateTime` instead of Unix timestamp, etc) and perform conversions during deserialization
- Keep the models as is and introduce helper getters/methods for converting props to higher level forms (as was demonstrated in the `Trade.DateTime` sample above)

I feel the strongest towards the second option as it would keep the source code uncluttered of helpers and would (I assume) suit for the widest range of consumers.

-----

PRs are always welcome :). I think adding helpers are fine now, but they might become redundant if core props of the models themselves will be changed later.

**Comment by hultqvist** [comment]
OK a PR coming up.

I would still suggest to keep the raw data since it helps when reading the official documentation. Perhaps the property names of the raw data gets identical names to the API and the converted names get dev friendly names.

**Comment by discosultan** [comment]
Great!

Thinking out loud here: if [extensions properties](https://github.com/dotnet/roslyn/issues/11159) were available, it would be neat if all the helpers could be brought in as extensions by a simple `using` statement. By having them as extensions would also clearly indicate to the user through intellisense that these props are not part of the native model. Unfortunately, they are not available yet and resorting to extension methods is probably not good user experience.

**Comment by discosultan** [comment]
I would like to keep the library relatively low level and instead incentivize to extend the models using extension methods from consuming libraries.

I really like the idea of:

```csharp
new KrakenClient(...).BTCEUR.GetRecentTrades(DateTime.UtcNow.AddDays(-1));
```

But have currently no plans to include it to the core. I'd prefer a higher level wrapper library.
